import type { RepositoryPulse } from "./types";

export const SAMPLE_REPOSITORY: RepositoryPulse = {
  root: "/Users/mira/Code/northstar",
  name: "northstar",
  scannedAt: "2026-08-28T14:32:00.000Z",
  warnings: [],
  worktrees: [
    {
      id: "wt-checkout",
      name: "checkout-retry",
      path: "/Users/mira/Code/northstar-checkout-retry",
      branch: "agent/checkout-retry",
      agent: "Claude Code",
      agentState: "blocked",
      updatedAt: "2026-08-28T14:30:00.000Z",
      dirty: 3,
      ahead: 2,
      behind: 0,
      detached: false,
      note: "Waiting for input",
    },
    {
      id: "wt-search",
      name: "search-index",
      path: "/Users/mira/Code/northstar-search-index",
      branch: "agent/search-index",
      agent: "Codex",
      agentState: "working",
      updatedAt: "2026-08-28T14:31:00.000Z",
      dirty: 6,
      ahead: 0,
      behind: 0,
      detached: false,
      note: "Running tests",
    },
    {
      id: "wt-invoices",
      name: "invoice-export",
      path: "/Users/mira/Code/northstar-invoice-export",
      branch: "agent/invoice-export",
      agent: "Gemini CLI",
      agentState: "idle",
      updatedAt: "2026-08-28T14:19:00.000Z",
      dirty: 0,
      ahead: 4,
      behind: 1,
      detached: false,
      note: "Stopped after commit",
    },
    {
      id: "wt-auth",
      name: "auth-cleanup",
      path: "/Users/mira/Code/northstar-auth-cleanup",
      branch: "agent/auth-cleanup",
      agent: "OpenCode",
      agentState: "idle",
      updatedAt: "2026-08-28T14:05:00.000Z",
      dirty: 0,
      ahead: 0,
      behind: 0,
      detached: false,
      note: "Ready for review",
    },
    {
      id: "wt-main",
      name: "northstar",
      path: "/Users/mira/Code/northstar",
      branch: "main",
      agent: "No adapter",
      agentState: "none",
      updatedAt: null,
      dirty: 1,
      ahead: 0,
      behind: 0,
      detached: false,
    },
  ],
};
